@include('layouts.mainsite.header')
<div class="front-page-info-top-block">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="front-page-info-top">
                    <div class="row align-items-center">
                        <div class="col-12 col-lg-12 col-xl-6">
                            <div class="front-page-info-top__left">
                                <div class="front-page-info-top-divider-block">
                                    <div class="front-page-info-top-divider"></div>
                                </div>
                                <div class="front-page-info-top-content">

                                    <div class="front-page-info-top-title-block">
                                        <h1 class="front-page-info-top-title">
                                            Affiliate Program.
                                            <div class="gradient-text-wrapper">
                                                <div class="gradient-text">Grow Your Network Income</div>
                                            </div>
                                        </h1>
                                    </div>
                                    <div class="front-page-info-top-descr-block">
                                        <div class="front-page-info-top-descr">
                                                Build your network and earn passive income through staking rewards, trading activity, and ecosystem participation generated by your referrals.

                                        </div>
                                    </div>
                                </div>
                                <div class="front-page-info-feature-items-block">
                                    <div class="front-page-info-feature-items">
                                        <div class="front-page-info-feature-item-wrapper">
                                            <div
                                                class="front-page-info-feature-item front-page-info-feature-item--affiliate-stats">
                                                <div class="front-page-info-feature-item__icon"></div>
                                                <div class="front-page-info-feature-item__text">Multiline structure
                                                </div>
                                            </div>
                                        </div>
                                        <div class="front-page-info-feature-item-wrapper">
                                            <div
                                                class="front-page-info-feature-item front-page-info-feature-item--affiliate-commission">
                                                <div class="front-page-info-feature-item__icon"></div>
                                                <div class="front-page-info-feature-item__text">Grow Your Network Income
                                                </div>
                                            </div>
                                        </div>
                                        <div class="front-page-info-feature-item-wrapper">
                                            <div
                                                class="front-page-info-feature-item front-page-info-feature-item--affiliate-bonuses">
                                                <div class="front-page-info-feature-item__icon"></div>
                                                <div class="front-page-info-feature-item__text">Build & Earn Together
                                                    USDT
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="front-page-info-top-buttons-block">
                                    <div class="front-page-info-top-buttons">
                                        <div class="front-page-info-top-button-wrapper">
                                            <a href="../sign-up/index.html"
                                                class="front-page-info-top-button green-gradient-btn iconed-btn">
                                                <div class="iconed-btn__text">Join Now</div>
                                                <div class="iconed-btn__icon"></div>
                                            </a>
                                        </div>
                                        <div
                                            class="front-page-info-top-button-wrapper d-none OORA3HideTabletAndMobile">
                                            <button type="button" data-bs-toggle="modal"
                                                data-bs-target="#modalDownload"
                                                class="download-button light-black-btn iconed-btn">
                                                <div class="iconed-btn__text">Download</div>
                                                <div class="iconed-btn__icon"></div>
                                            </button>
                                        </div>
                                        <div
                                            class="front-page-info-top-button-wrapper d-none OORA3ShowTabletAndMobile">
                                            <a href="https://t.me/OORA3_crypto_bot/app?startapp=" target="_blank"
                                                class="telegram-app-button iconed-btn">
                                                <div class="iconed-btn__icon"></div>
                                                <div class="iconed-btn__text">Telegram app</div>
                                            </a>
                                        </div>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-12 col-xl-6">
                            <div class="front-page-info-top__right">

                                <div class="fp-infographic-block">
                                    <div class="fp-infographic fp-infographic--affiliate">
                                        <div class="fp-infographic__bg">
                                            <div class="fp-infographic__circles">
                                                <div class="fp-infographic__circle fp-infographic__circle--outer">
                                                </div>
                                                <div class="fp-infographic__circle fp-infographic__circle--middle">
                                                </div>
                                                <div class="fp-infographic__circle fp-infographic__circle--inner">
                                                </div>
                                            </div>
                                            <div class="fp-infographic__poiners">
                                                <div class="fp-infographic__pointer fp-infographic__pointer--left-top">
                                                </div>
                                                <div class="fp-infographic__pointer fp-infographic__pointer--right-top">
                                                </div>
                                                <div
                                                    class="fp-infographic__pointer fp-infographic__pointer--right-bottom">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="fp-infographic__content">
                                            <div class="fp-infographic__center-icon-block">
                                                <div class="fp-infographic__center-icon">
                                                </div>
                                            </div>
                                            <div class="fp-infographic-items">
                                                <div class="fp-infographic-item fp-infographic-item--left-top">
                                                    <div class="fp-infographic-item__inner">
                                                        <div
                                                            class="fp-infographic-item__info fp-infographic-item__info--affiliate-bonus">
                                                            <div class="fp-infographic-item__info__icon-block">
                                                                <div
                                                                    class="fp-infographic-item__info__icon fp-infographic-item__info__icon--affiliate-bonus">
                                                                    <div class="fp-infographic-item__info__icon__image">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="fp-infographic-item__info__content">
                                                                <div class="fp-infographic-item__info__title">
                                                                  Level Growth
                                                                </div>
                                                                <div class="fp-infographic-item__info__value">
                                                                   OORA3 1 → OORA3 2
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="fp-infographic-item fp-infographic-item--right-top">
                                                    <div class="fp-infographic-item__inner">
                                                        <div class="fp-infographic-item__top">
                                                            <div class="fp-infographic-item__top-left">
                                                                <div class="fp-infographic-item__top-title">
                                                                    New partner
                                                                </div>
                                                            </div>
                                                            <div class="fp-infographic-item__top-right">
                                                                <div class="fp-infographic-item__top-label-wrapper">
                                                                    <div
                                                                        class="fp-infographic-item__top-label fp-infographic-item__top-label--green">
                                                                        Active</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="fp-infographic-item__info fp-infographic-item__info--affiliate-referral">
                                                            <div class="fp-infographic-item__info__icon-block">
                                                                <div
                                                                    class="fp-infographic-item__info__icon fp-infographic-item__info__icon--affiliate-referral">
                                                                    <div class="fp-infographic-item__info__icon__image">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="fp-infographic-item__info__content">
                                                                <div class="fp-infographic-item__info__title">
                                                                Earn Up to 40% Commission

                                                                </div>
                                                                <div class="fp-infographic-item__info__value">
                                                                    Real-Time Rewards
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="fp-infographic-item fp-infographic-item--right-bottom">
                                                    <div class="fp-infographic-item__inner">

                                                        <div
                                                            class="fp-infographic-item__info fp-infographic-item__info--affiliate-upgrade">
                                                            <div class="fp-infographic-item__info__icon-block">
                                                                <div
                                                                    class="fp-infographic-item__info__icon fp-infographic-item__info__icon--affiliate-upgrade">
                                                                    <div
                                                                        class="fp-infographic-item__info__icon__image">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="fp-infographic-item__info__content">
                                                                <div class="fp-infographic-item__info__title">
                                                                    Сareer growth
                                                                </div>
                                                                <div class="fp-infographic-item__info-level-block">
                                                                    <div class="fp-infographic-item__info-levels">
                                                                        <div
                                                                            class="fp-infographic-item__info-level fp-infographic-item__info-level--current">
                                                                         Your Growth</div>
                                                                        <div
                                                                            class="fp-infographic-item__info-level-arrow">
                                                                        </div>
                                                                        <div
                                                                            class="fp-infographic-item__info-level fp-infographic-item__info-level--next">
                                                                            Next Level</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>


                                                        <div
                                                            class="fp-infographic-item__progress fp-infographic-item__progress--upgrade">
                                                            <div class="fp-infographic-item__progress__loaded"
                                                                style="width: 80%;">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>





                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="front-page-block">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="front-page">
                    <div class="front-page__fullwidth">
                        <div class="front-page__content">

                            <div class="front-features-block">
                                <div class="front-features">
                                    <div class="front-features-top-block">
                                        <div class="front-features-top">
                                            <div class="front-features-top__left">
                                                <h2 class="front-features-top__title">
                                                    Why should you join the affiliate club?
                                                </h2>
                                                <div class="front-features-top__descr">
                                                    Key benefits of the OORA3 affiliate program for those looking to
                                                    earn by promoting our products.
                                                </div>

                                            </div>
                                            <div class="front-features-top__right">
                                                <div class="more-link-block">
                                                    <a href="javascript:void(0)"
                                                        data-scroll=".globalPageAffiliateProgramHowTo"
                                                        class="more-link">How is the affiliate reward calculated?</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    
                                  <div class="front-feature-items-block">
    <div class="front-feature-items">

        <!-- OORA3 CHAT -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                  <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--share-2.svg">
                </div>
                <div class="front-feature-item__title">
                    OORA3 Chat
                </div>
                <div class="front-feature-item__descr">
                    A decentralized communication layer enabling secure, private, and peer-to-peer messaging without centralized control.
                </div>
            </div>
        </div>

        <!-- OORA3 MEET -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                  <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--git-fork.svg">

                </div>
                <div class="front-feature-item__title">
                    OORA3 Meet
                </div>
                <div class="front-feature-item__descr">
                    A decentralized video collaboration platform for secure meetings, governance discussions, and global team communication.
                </div>
            </div>
        </div>

        <!-- OORA3 AI -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                  <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--sliders-horizontal.svg">

                </div>
                <div class="front-feature-item__title">
                    OORA3 AI
                </div>
                <div class="front-feature-item__descr">
                    Intelligent ecosystem engine providing predictive analytics, automation, and data-driven insights for optimized performance.
                </div>
            </div>
        </div>

        <!-- OORA3 DEX -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                   <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--chart-column.svg">

                </div>
                <div class="front-feature-item__title">
                    OORA3 DEX
                </div>
                <div class="front-feature-item__descr">
                    Integrated decentralized exchange enabling secure, fast, and transparent trading without intermediaries.
                </div>
            </div>
        </div>

        <!-- OORA3 COIN -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                  <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--chart-pie.svg">

                </div>
                <div class="front-feature-item__title">
                    OORA3 Coin
                </div>
                <div class="front-feature-item__descr">
                    Native utility token powering transactions, rewards, governance, and ecosystem participation across all platforms.
                </div>
            </div>
        </div>

        <!-- OORA3 SCAN -->
        <div class="front-feature-item-wrapper">
            <div class="front-feature-item">
                <div class="front-feature-item__icon">
                 <img src="{{asset('')}}assets/oora3/images/svg/front/front-feature-item-icon--trophy.svg">

                </div>
                <div class="front-feature-item__title">
                    OORA3 Scan
                </div>
                <div class="front-feature-item__descr">
                    Blockchain explorer providing real-time transaction tracking, wallet visibility, and full transparency across the network.
                </div>
            </div>
        </div>

    </div>
</div>
                                </div>
                            </div>

                          


                            <div class="front-section-block">

                                <div class="front-section-top-block">
                                    <div class="front-section-top">
                                        <div class="front-section-top__left">

                                            <div class="front-section-title-block">
                                                <h2 class="front-section-title">
                                                    Achievement bonuses
                                                </h2>
                                            </div>
                                            <div class="front-section-descr-block">
                                                <div class="front-section-descr">
                                                    Reach your profit targets and get instant cash bonuses for every
                                                    affiliate level upgrade.
                                                </div>
                                            </div>

                                        </div>
                                        <div class="front-section-top__right">
                                            <div class="aff-reward-button-block">
                                                <div
                                                    class="aff-reward-button iconed-btn light-black-btn button--small">
                                                    <div class="iconed-btn__icon"></div>
                                                    <div class="iconed-btn__text">
                                                        Additional bonuses
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="front-section">


                                    <div class="aff-bonus-table-block">
                                        <div class="aff-bonus-table">
                                            <div class="aff-bonus-table-heading">
                                                <div class="aff-bonus-t-h-cell aff-bonus-t-h-cell--level-name">
                                                    Affiliate level
                                                </div>
                                                <div class="aff-bonus-t-h-cell aff-bonus-t-h-cell--req-profit">
                                                    business 
                                                </div>
                                                <div class="aff-bonus-t-h-cell aff-bonus-t-h-cell--bonus">
                                                    Distribution 
                                                </div>
                                            </div>

                                            
                                            <div class="aff-bonus-table-items">
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 1</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate Business 
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $100-$5k
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        5% 
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 2</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $5K - $15K
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        10%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 3</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $25k - $50K
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        20%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 4</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $50K - $100K
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        25%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 5</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $100K - $500K
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        30%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 6</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $500K - $1Mn
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        35%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 7</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $1Mn - $2.5Mn
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        45%
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 8</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $2.5Mn - $5Mn
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        50%
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 9</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $5Mn - $20Mn
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        55% 
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="aff-bonus-table-item ">
                                                    <div class="aff-bonus-table-item__inner">
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--level-name">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate level
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__name-block">
                                                                    <div class="aff-bonus-t-i-cell__name-panel">
                                                                        <div class="aff-bonus-t-i-cell__name-wrapper">
                                                                            <div class="aff-bonus-t-i-cell__name">
                                                                                OORA3 10</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div
                                                            class="aff-bonus-t-i-cell aff-bonus-t-i-cell--req-profit">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Affiliate business
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__value">
                                                                    $20Mn & above
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="aff-bonus-t-i-cell aff-bonus-t-i-cell--bonus">
                                                            <div class="aff-bonus-t-i-cell__title">
                                                                Distribution
                                                            </div>
                                                            <div class="aff-bonus-t-i-cell__content">
                                                                <div class="aff-bonus-t-i-cell__bonus ">
                                                                    <div class="aff-bonus-t-i-cell__bonus-text">
                                                                        60 %
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                              



                                            </div>
                                        </div>
                                    </div>



                                </div>
                            </div>




                         <div class="front-cta-block">
    <div class="front-cta">

        <div class="front-cta__title-block">
            <div class="h1 front-cta__title">
                Build Your Network. Maximize Your Earnings.
            </div>
        </div>

        <div class="front-cta__descr-block">
            <div class="front-cta__descr">
                Grow your business volume and unlock higher referral rewards. Earn up to 60% based on your network performance with a transparent and scalable reward distribution system.
            </div>
        </div>

        <div class="front-cta-features-block">
            <div class="front-cta-features">

                <div class="front-cta-feature-wrapper">
                    <div class="front-cta-feature">
                        <div class="front-cta-feature__icon"></div>
                        <div class="front-cta-feature__text">
                            Multi-level referral structure
                        </div>
                    </div>
                </div>

                <div class="front-cta-feature-wrapper">
                    <div class="front-cta-feature">
                        <div class="front-cta-feature__icon"></div>
                        <div class="front-cta-feature__text">
                            Earn up to 60% rewards
                        </div>
                    </div>
                </div>

                <div class="front-cta-feature-wrapper">
                    <div class="front-cta-feature">
                        <div class="front-cta-feature__icon"></div>
                        <div class="front-cta-feature__text">
                            Volume-based reward system
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="front-cta-buttons-block">
            <div class="front-cta-buttons">

                <div class="front-cta-button-wrapper">
                    <a href="../sign-up/index.html"
                        class="front-cta-button green-gradient-btn iconed-btn">
                        <div class="iconed-btn__text">Start Earning</div>
                        <div class="iconed-btn__icon"></div>
                    </a>
                </div>

                <div class="front-cta-button-wrapper d-none OORA3HideTabletAndMobile">
                    <button type="button" data-bs-toggle="modal"
                        data-bs-target="#modalDownload"
                        class="download-button light-black-btn iconed-btn">
                        <div class="iconed-btn__text">Download</div>
                        <div class="iconed-btn__icon"></div>
                    </button>
                </div>

                <div class="front-cta-button-wrapper d-none OORA3ShowTabletAndMobile">
                    <a href="https://t.me/OORA3_crypto_bot/app?startapp="
                        target="_blank" class="telegram-app-button iconed-btn">
                        <div class="iconed-btn__icon"></div>
                        <div class="iconed-btn__text">Open App</div>
                    </a>
                </div>

            </div>
        </div>

    </div>
</div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@include('layouts.mainsite.footer')